=== Zurich1994/Bpmx3_dev/WebRoot/WEB-INF/classes/template/index/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.jee-soft.cn/index"
    targetNamespace="http://www.jee-soft.cn/index" elementFormDefault="qualified">
    <xs:element name="indexColumns">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="indexColumn" type="indexColumn" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="indexColumn">
        <xs:attribute name="name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>栏目名称.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="alias" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>栏目别名.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="catalog" type="xs:long">
            <xs:annotation>
                <xs:documentation>栏目分类.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="colType" type="colType"  use="required">
            <xs:annotation>
                <xs:documentation>栏目类型.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="dataMode" type="dataMode"  use="required">
            <xs:annotation>
                <xs:documentation>数据加载方式.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="dataFrom" type="xs:string">
            <xs:annotation>
                <xs:documentation>数据来源.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="dsAlias" type="xs:string" >
            <xs:annotation>
                <xs:documentation>数据别名.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="dsName" type="xs:string" >
            <xs:annotation>
                <xs:documentation>数据源名称.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        
        <xs:attribute name="colHeight" type="xs:string">
            <xs:annotation>
                <xs:documentation>栏目高度.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="colUrl" type="xs:string" >
            <xs:annotation>
                <xs:documentation>栏目url.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="templateHtml" type="xs:string"  >
            <xs:annotation>
                <xs:documentation>栏目模版.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="isPublic" type="xs:short"  use="required" >
            <xs:annotation>
                <xs:documentation>是否公共栏目.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="orgId" type="xs:long" >
            <xs:annotation>
                <xs:documentation>所属组织ID.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="supportRefesh" type="xs:short" default="0"  >
            <xs:annotation>
                <xs:documentation>是否支持刷新.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="refeshTime" type="xs:int" >
            <xs:annotation>
                <xs:documentation>刷新时间.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="showEffect" type="showEffect"  use="required" >
            <xs:annotation>
                <xs:documentation>展示效果.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="memo" type="xs:string" >
            <xs:annotation>
                <xs:documentation>描述.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        
    </xs:complexType>
    <!-- 栏目类型 -->
    <xs:simpleType name="colType">
        <xs:annotation>
            <xs:documentation>栏目类型</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:short">
            <xs:enumeration value="0" ><xs:annotation><xs:documentation>一般类型栏目</xs:documentation></xs:annotation></xs:enumeration>
            <xs:enumeration value="1" ><xs:annotation><xs:documentation>图表类型栏目</xs:documentation></xs:annotation></xs:enumeration>
            <xs:enumeration value="2" ><xs:annotation><xs:documentation>日历类型栏目</xs:documentation></xs:annotation></xs:enumeration>
            <xs:enumeration value="3" ><xs:annotation><xs:documentation>滚动类型栏目</xs:documentation></xs:annotation></xs:enumeration>      
        </xs:restriction>
    </xs:simpleType>
    <!-- 数据加载方式 -->
    <xs:simpleType name="dataMode">
        <xs:annotation>
            <xs:documentation>数据加载方式.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:short">
            <xs:enumeration value="0" ><xs:annotation><xs:documentation>服务方法</xs:documentation></xs:annotation></xs:enumeration>
            <xs:enumeration value="1" ><xs:annotation><xs:documentation>自定义查询</xs:documentation></xs:annotation></xs:enumeration>        
        </xs:restriction>
    </xs:simpleType>
    <!-- 数据加载方式 -->
    <xs:simpleType name="showEffect">
        <xs:annotation>
            <xs:documentation>展示效果.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:short">
            <xs:enumeration value="0" ><xs:annotation><xs:documentation>默认效果</xs:documentation></xs:annotation></xs:enumeration>
            <xs:enumeration value="1" ><xs:annotation><xs:documentation>走马灯</xs:documentation></xs:annotation></xs:enumeration>        
            <xs:enumeration value="2" ><xs:annotation><xs:documentation>幻灯片</xs:documentation></xs:annotation></xs:enumeration>             
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Zurich1994/Bpmx3_dev/resources/template/index/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<indexColumns xmlns="http://www.jee-soft.cn/index"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.jee-soft.cn/index index.xsd">
	<indexColumn name="个人信息" 	alias="userInfo" 		 colType="0" dataMode="0" dataFrom="indexService.userInfo" 	isPublic="1" supportRefesh="0" showEffect="0"/>
	<indexColumn name="未读消息" 	alias="getMessage" 		 colType="0" dataMode="0" dataFrom="indexService.getMessage" 	 colUrl="/platform/system/messageReceiver/list.ht" isPublic="1" supportRefesh="0" showEffect="1"/>
	<indexColumn name="待办事宜" 	alias="pendingMatters" 	 colType="0" dataMode="0" dataFrom="indexService.pendingMatters"  colUrl="/platform/bpm/task/pendingMatters.ht"	isPublic="1" supportRefesh="0" showEffect="0"/>
	<indexColumn name="已办事宜" 	alias="alreadyMatters" 	 colType="0" dataMode="0" dataFrom="indexService.alreadyMatters"  colUrl="/platform/bpm/processRun/alreadyMatters.ht" isPublic="1" supportRefesh="0" showEffect="0"/>
	<indexColumn name="办结事宜" 	alias="completedMatters" colType="0" dataMode="0" dataFrom="indexService.completedMatters" 	 colUrl="/platform/bpm/processRun/completedMatters.ht" isPublic="1" supportRefesh="0" showEffect="0"/>
	<indexColumn name="我的办结" 	alias="myCompleted" 	 colType="0" dataMode="0" dataFrom="indexService.myCompleted"  colUrl="/platform/bpm/processRun/myCompleted.ht"	isPublic="1" supportRefesh="0" showEffect="0"/>
	<indexColumn name="我的请求" 	alias="myRequest" 		 colType="0" dataMode="0" dataFrom="indexService.myStart"  colUrl="/platform/bpm/processRun/myRequest.ht" isPublic="1" supportRefesh="0" showEffect="0"/>	
	<indexColumn name="新建流程" 	alias="newProcess" 	 colType="0" dataMode="0" dataFrom="indexService.myProcess" 	 colUrl="/platform/bpm/bpmDefinition/forMe.ht" isPublic="1" supportRefesh="0" showEffect="0"/>
	<indexColumn name="折线图例子" alias="lineChart" 		 colType="1" dataMode="0" dataFrom="indexService.lineChart"  	isPublic="1" supportRefesh="0" showEffect="0"/>
	<indexColumn name="柱状图例子" alias="barChart" 		 colType="1" dataMode="0" dataFrom="indexService.barChart"   isPublic="1" supportRefesh="1" showEffect="0"/>
	<indexColumn name="幻灯片例子" alias="slide" 		     colType="0" dataMode="0"  colHeight="450" isPublic="1" supportRefesh="0" showEffect="2"/>
	<indexColumn name="我的日程 "  	alias="myCalendar" 		 colType="2" dataMode="0" dataFrom="indexService.myCalendar"  	isPublic="1" supportRefesh="0" showEffect="0"/>
	<indexColumn name="信息盒" 	alias="infobox" 		 colType="0" dataMode="0" dataFrom="indexService.getInfobox" 	isPublic="1" supportRefesh="0" showEffect="0"/>
</indexColumns>
